;Design and develop an assembly language program to read the current time and Date from the system and display it in the standard format on the screen.
				
PRINT MACRO NUM       ;MACRO TO UNPACK THE NUMBERS AND DISPLAY IT ON SCREEN
	MOV AL,NUM	;NUM IS THE PLACEHOLDER TO RECEIVE THE PASSED NUMBER. STORE 8-BIT NUMBER IN AL 
	AAM	       	;AH=AL/10 , AL=AL%10 I.E UNPACKS THE NUMBER
	MOV BX,AX   	;STORE COPY OF THE UNPACKED NUMBER IN AX
	ADD BX,3030H 	; ADD 3030H TO THE UNPACKED NUMBER TO CONVERT IT INTO THE NUMBER’S ASCII VALUE
	MOV DL,BH      	;STORE THE ASCII VALUES OF 1ST DIGIT IN DL 
	MOV AH,02H	;AND CALL FUNCTION 02H OF INT 21H TO DISPLAY THE CHARACTER ON SCREEN
	INT 21H
	MOV DL,BL	;STORE THE ASCII VALUES OF 2ND  DIGIT IN DL
	MOV AH,02H	;AND CALL FUNCTION 02H OF INT 21H TO DISPLAY THE CHARACTER ON SCREEN
	INT 21H
ENDM

COLON MACRO	 ;MACRO TO DISPLAY : ON SCREEN			
         MOV DL,':'                  ;LOAD DL WITH ASCII VALUE OF “:”                          
	MOV AH,02H 	 ;AND CALL FUNCTION 02H OF INT 21H TO DISPLAY THE CHARACTER ON SCREEN		      
	INT 21H             			            		    
ENDM

SLASH MACRO                   ;MACRO TO DISPLAY / ON SCREEN
        MOV DL,'/'	  ;LOAD DL WITH ASCII VALUE OF “/”                          
	MOV AH,02H	  ;AND CALL FUNCTION 02H OF INT 21H TO DISPLAY THE CHARACTER ON SCREEN
	INT 21H
ENDM

DISPLAY MACRO MSG			            ;MACRO TO DISPLAY A STRING.
                  LEA DX,MSG			            ; STARTING ADDRESS OF THE STRING TO BE DISPLAYED IS LOADED IN DX
                  MOV AH,09H			            ; FUNCTION TO DISPLAY STRING UNDER INT21H
                  INT 21H
ENDM

DATA SEGMENT
            MSG1 DB 'SYSTEM TIME IS $'
            MSG2 DB 10,13, 'SYSTEM DATE IS $'     ;10,13 BRINGS CURSOR TO NEXT LINE
DATA ENDS

ASSUME CS:CODE,DS:DATA

CODE SEGMENT
START:	MOV AX,DATA	;LOAD THE DATA SEGMENT BASE ADDRESS INTO DS REGISTER USING AX
                  	MOV DS,AX  
                	DISPLAY MSG1	;DISPLAY MSG1
                	MOV AH,2CH           ;FUNCTION 2CH OF INT 21H RETURNS TIME IN FORMAT: 
                           INT 21H		;CH=HR, CL=MIN, DH=SEC, DL= 1/100 SEC
                           PRINT CH	;DISPLAY HOUR
                           COLON		;DISPLAY :	
                           PRINT CL		;DISPLAY MINUTE
                           DISPLAY MSG2   	;DISPLAY MSG2 USING FUNCTION 09H OF INT 21H
                           MOV AH,2AH   	;FUNCTION 2AH OF INT 21H WILL RETURN SYSTEM DATE IN FORMAT:
                           INT 21H		; DL=DAY, DH=MONTH, CX=YEAR
                           PRINT DL          	;DISPLAY DAY
                           SLASH		;DISPLAY /
                           PRINT DH	;DISPLAY MONTH
                           SLASH		;DISPLAY /
                           ADD CX,0F830H	;YEAR CONVERSION
	                  PRINT CL		;DISPLAY YEAR 
                           MOV AH,4CH	;FUNCTION 4CH OF INT 21H EXITS THE CURRENT PROGRAM. 
                           INT 21H
CODE ENDS 
END START

