;Design and develop an assembly program to read the status of two 8-bit inputs (X & Y)    from the Logic Controller Interface and display X*Y
DATA SEGMENT
PORTA  EQU 0E880H	;8255 PORT A PORT# E880H GIVEN THE NAME PORTA
PORTB  EQU  0E881H	;8255 PORT B PORT# E881H GIVEN THE NAME PORTA
CR  EQU  0E883H		;8255 CONTROL WORD ADDRESS E883H GIVEN THE NAME CR
DATA ENDS

ASSUME CS:CODE,DS:DATA  

CODE SEGMENT
START: 	MOV AX,DATA
  	MOV DS,AX
MOV AL,82H; 82H IS COPIED TO AL TO LOAD INTO CR FOR SETTING PORT A & C AS OUTPUT & B AS INPUT PORTS
MOV DX,CR	;PORT ADDRESS IS 16 BIT, THEREFORE DX IS USED TO HOLD IT FOR IN & OUT
OUT DX,AL	;8 BIT DATA IN AL IS SENT TO CR WHOSE 16-BIT ADDRESS IS IN DX.
MOV DX,PORTB	;READ DATA INPUT AT PORT B INTO AL REGISTER USING IN INSTRUCTION
IN AL,DX
MOV BL,AL	;COPY OF THE 8 BIT DATA IN AL IS MOVED INTO BL
MOV AH,01H	;CALL A KEYBOARD INTERRUPT TO HALT CODE UNTIL USER SETS 2ND NUMBER IN THE
INT 21H		;LOGIC CONTROLLER KIT.EXECUTION PROCEEDS AFTER A KEY PRESS ON KEYBOARD
MOV DX,PORTB	;READ THE SECOND 8 BIT NUMBER FROM PORT B INTO AL
IN AL,DX	
MUL BL		;MULTIPLY THE 8-BIT DATA IN AL & BL.MAY GIVE A 16 BIT RESULT AS WELL.
MOV DX,PORTA	;LOWER BYTE OF RESULT IS MOVED INTO OUTPUT PORT A. OUTPIT WILL BE SEEN
OUT DX,AL	;IN THE 8 LEDS AT THE OUTPUT
PUSH AX		;PUSH THE DATA ON STACK AS KEYBOARD INTERRUPT WILL BE CALLED AND AH VALUE
MOV AH,01H	;WILL BE LOST WHEN 01H IS MOVED INTO AH. KEYBOIARD INTERRUPT IS CALLED TO 
INT 21H		;HALT CODE UNTIL USER PRESSES KEY AFTER DISPLAYING LOWER BYTE
POP AX		;AFTER USER PRESSES THE KEY THE AX VALUE IS POPPED BACK FROM THE STACK
MOV AL,AH	;HIGHER BYTE IS NOW SENT TO THE OUTPUT PORT A
MOV DX,PORTA
OUT DX,AL
MOV AH,4CH	;INTERRUPT TO EXIT THE PROGRAM
INT 21H
CODE ENDS 
END START
